# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'books.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\x12\x05\x62ooks\"\x19\n\x0b\x42ookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x0e\n\x0c\x45mptyRequest\"S\n\x0c\x42ookResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x18\n\x10publication_date\x18\x04 \x01(\t\"K\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x18\n\x10publication_date\x18\x04 \x01(\t\".\n\x10\x42ookListResponse\x12\x1a\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0b.books.Book2\x82\x01\n\x0b\x42ookService\x12\x36\n\x0bGetBookById\x12\x12.books.BookRequest\x1a\x13.books.BookResponse\x12;\n\x0bGetAllBooks\x12\x13.books.EmptyRequest\x1a\x17.books.BookListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKREQUEST']._serialized_start=22
  _globals['_BOOKREQUEST']._serialized_end=47
  _globals['_EMPTYREQUEST']._serialized_start=49
  _globals['_EMPTYREQUEST']._serialized_end=63
  _globals['_BOOKRESPONSE']._serialized_start=65
  _globals['_BOOKRESPONSE']._serialized_end=148
  _globals['_BOOK']._serialized_start=150
  _globals['_BOOK']._serialized_end=225
  _globals['_BOOKLISTRESPONSE']._serialized_start=227
  _globals['_BOOKLISTRESPONSE']._serialized_end=273
  _globals['_BOOKSERVICE']._serialized_start=276
  _globals['_BOOKSERVICE']._serialized_end=406
# @@protoc_insertion_point(module_scope)
